platform :ios, '9.0'

target 'Test' do
  use_frameworks!

  # Pods for Test

pod 'Alamofire', '~> 4.3.0'
pod 'RAMAnimatedTabBarController'
pod 'XCGLogger','~> 4.0.0'
pod 'QMUIKit', '~> 1.3.0'
pod 'SlideMenuControllerSwift'
pod 'RDVTabBarController'

  target 'TestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
