//
//  TheImage.swift
//  ProjectName
//
//  Created by AuthorName on 13/07/2017.
//  Copyright © 2017 CompanyName. All rights reserved.
//
//  Generated by PaintCode
//  http://www.paintcodeapp.com
//



import UIKit

public class TheImage : NSObject {

    class func useFitImage(width: CGFloat ,height: CGFloat) -> UIImage {
        
        var w = 0.0
        var h = 0.0
        
        if width > 50 {
            w = Double(width*2)
            h = Double(height*2)
        }else {
            w = Double(width*3)
            h = Double(height*3)
        }
        
        UIGraphicsBeginImageContextWithOptions(CGSize.init(width: w, height: h), false, 1.0)
        TheImage.drawCanvas2(frame: CGRect.init(x: 0, y: 0, width: w, height: h), resizing: .aspectFit)
        return UIGraphicsGetImageFromCurrentImageContext()!;
    }
    
    //// Drawing Methods

    public dynamic class func drawCanvas1(frame targetFrame: CGRect = CGRect(x: 0, y: 0, width: 28, height: 28), resizing: ResizingBehavior = .aspectFit) {
        //// General Declarations
        let context = UIGraphicsGetCurrentContext()!
        
        //// Resize to Target Frame
        context.saveGState()
        let resizedFrame: CGRect = resizing.apply(rect: CGRect(x: 0, y: 0, width: 28, height: 28), target: targetFrame)
        context.translateBy(x: resizedFrame.minX, y: resizedFrame.minY)
        context.scaleBy(x: resizedFrame.width / 28, y: resizedFrame.height / 28)


        //// Color Declarations
        let color = UIColor(red: 0.965, green: 0.031, blue: 0.031, alpha: 1.000)

        //// Oval Drawing
        let ovalPath = UIBezierPath(ovalIn: CGRect(x: 0, y: 0, width: 28, height: 28))
        UIColor.gray.setFill()
        ovalPath.fill()


        //// Star Drawing
        let starPath = UIBezierPath()
        starPath.move(to: CGPoint(x: 14, y: 6))
        starPath.addLine(to: CGPoint(x: 16.82, y: 10.12))
        starPath.addLine(to: CGPoint(x: 21.61, y: 11.53))
        starPath.addLine(to: CGPoint(x: 18.57, y: 15.48))
        starPath.addLine(to: CGPoint(x: 18.7, y: 20.47))
        starPath.addLine(to: CGPoint(x: 14, y: 18.8))
        starPath.addLine(to: CGPoint(x: 9.3, y: 20.47))
        starPath.addLine(to: CGPoint(x: 9.43, y: 15.48))
        starPath.addLine(to: CGPoint(x: 6.39, y: 11.53))
        starPath.addLine(to: CGPoint(x: 11.18, y: 10.12))
        starPath.close()
        color.setFill()
        starPath.fill()
        
        context.restoreGState()

    }

    public dynamic class func drawCanvas2(frame targetFrame: CGRect = CGRect(x: 0, y: 0, width: 200, height: 200), resizing: ResizingBehavior = .aspectFit) {
        //// General Declarations
        let context = UIGraphicsGetCurrentContext()!
        
        //// Resize to Target Frame
        context.saveGState()
        let resizedFrame: CGRect = resizing.apply(rect: CGRect(x: 0, y: 0, width: 200, height: 200), target: targetFrame)
        context.translateBy(x: resizedFrame.minX, y: resizedFrame.minY)
        context.scaleBy(x: resizedFrame.width / 200, y: resizedFrame.height / 200)



        //// Image Declarations
        let screenShot20170713At102217AM = UIImage(named: "screenShot20170713At102217AM.png")!

        //// Bezier Drawing
        let bezierPath = UIBezierPath()
        bezierPath.move(to: CGPoint(x: 198, y: 100))
        bezierPath.addCurve(to: CGPoint(x: 99, y: 200), controlPoint1: CGPoint(x: 198, y: 155.23), controlPoint2: CGPoint(x: 153.68, y: 200))
        bezierPath.addCurve(to: CGPoint(x: 0, y: 100), controlPoint1: CGPoint(x: 44.32, y: 200), controlPoint2: CGPoint(x: 0, y: 155.23))
        bezierPath.addCurve(to: CGPoint(x: 39.39, y: 20.15), controlPoint1: CGPoint(x: 0, y: 67.38), controlPoint2: CGPoint(x: 15.46, y: 38.41))
        bezierPath.addCurve(to: CGPoint(x: 99, y: 0), controlPoint1: CGPoint(x: 55.97, y: 7.5), controlPoint2: CGPoint(x: 76.62, y: 0))
        bezierPath.addCurve(to: CGPoint(x: 198, y: 100), controlPoint1: CGPoint(x: 153.68, y: 0), controlPoint2: CGPoint(x: 198, y: 44.77))
        bezierPath.close()
        context.saveGState()
        bezierPath.addClip()
        context.translateBy(x: 0, y: 0)
        context.scaleBy(x: 1, y: -1)
        context.translateBy(x: 0, y: -screenShot20170713At102217AM.size.height)
        context.draw(screenShot20170713At102217AM.cgImage!, in: CGRect(x: 0, y: 0, width: screenShot20170713At102217AM.size.width, height: screenShot20170713At102217AM.size.height))
        context.restoreGState()
        
        context.restoreGState()

    }




    @objc(TheImageResizingBehavior)
    public enum ResizingBehavior: Int {
        case aspectFit /// The content is proportionally resized to fit into the target rectangle.
        case aspectFill /// The content is proportionally resized to completely fill the target rectangle.
        case stretch /// The content is stretched to match the entire target rectangle.
        case center /// The content is centered in the target rectangle, but it is NOT resized.

        public func apply(rect: CGRect, target: CGRect) -> CGRect {
            if rect == target || target == CGRect.zero {
                return rect
            }

            var scales = CGSize.zero
            scales.width = abs(target.width / rect.width)
            scales.height = abs(target.height / rect.height)

            switch self {
                case .aspectFit:
                    scales.width = min(scales.width, scales.height)
                    scales.height = scales.width
                case .aspectFill:
                    scales.width = max(scales.width, scales.height)
                    scales.height = scales.width
                case .stretch:
                    break
                case .center:
                    scales.width = 1
                    scales.height = 1
            }

            var result = rect.standardized
            result.size.width *= scales.width
            result.size.height *= scales.height
            result.origin.x = target.minX + (target.width - result.width) / 2
            result.origin.y = target.minY + (target.height - result.height) / 2
            return result
        }
    }
}
